### ISSUE TITLE
saml.security.http.logout does not exist

### ISSUE THREAD

**Issue by paharasse** [hslavich/OneloginSamlBundle#104]
Hello,

I have this error when I activate logout config in my firewall : `Service "hslavich_onelogin_saml.saml_logout": Parent definition "saml.security.http.logout" does not exist.`
I have searched in my project and there is no place where saml.security.http.logout service is defined. Can you tell us how to configure it?
Thank you.

My firewall config :
```
firewalls:
        secured_area:
            pattern: ^/
            anonymous: true
            provider: fos_userbundle
            switch_user: { role: ROLE_ADMIN }
            saml:
                use_attribute_friendly_name: true
                user_factory: custo_user_provider
                check_path: saml_acs
                login_path: saml_login
            logout:
                path: saml_logout
```
