### ISSUE TITLE
Node RSAKeyValue from my Idp's SAML metadatas

### ISSUE THREAD

**Issue by MatthieuCt** [hslavich/OneloginSamlBundle#111]
Hi,

I'm trying to use your bundle inside one of my project but I've reached a deadlock.

My idp's metadata contains node called ```RSAKeyValue```. Here is an example of the KeyDescriptor:

```xml
<KeyDescriptor use="encryption">
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
          <ds:KeyValue>
	<RSAKeyValue xmlns="http://www.w3.org/2000/09/xmldsig#">
		<Modulus>Modulus Content</Modulus>
		<Exponent>AQAB</Exponent>
	</RSAKeyValue>
</ds:KeyValue>
      </ds:KeyInfo>
    </KeyDescriptor>
```

Does OneloginSaml support RSAKeyValue node ?

If so how am I supposed to write the idp configuration yaml ? I currently have something like this:

```yaml
    idp:
        entityId: 'https://app.com/saml/metadata'
        singleSignOnService:
            url: 'https://app.com/saml/singleSignOn'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        singleLogoutService:
            url: 'https://app.com/saml/singleLogout'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        x509certMulti:
            signing:
                - 'x509cert'
            encryption:
                - 'Modulus content'
```
