### ISSUE TITLE
Error in definition of provider in 1.6.2

### ISSUE THREAD

**Issue by rmdefi** [hslavich/OneloginSamlBundle#175]
Using version 1.6.2 (with symfony 4.4.25), running cache:clear gives me an error:

```
In Definition.php line 292:
                                                                                                        
  [Symfony\Component\DependencyInjection\Exception\OutOfBoundsException]                                
  Service "security.authentication.provider.saml.dashboard": The index "1" is not in the range [0, 0].  
```

This related to the change, in version 1.6.0, in Hslavich\OneloginSamlBundle\DependencyInjection\Security\Factory\SamlFactory::createAuthProvider which changed an addArgument to a replaceArgument.
But in Resources/config/services.yml, hslavich_onelogin_saml.saml_provider only defines one argument.

So, I suppose either the definition in services.yml should define a second argument (to be replaced), or createAuthProvider should be changed back to using addArgument?

**Comment by rmdefi** [comment]
I have a workaround, to redefine (in my own services) the service with two arguments:

```yaml
services:
    class: Hslavich\OneloginSamlBundle\Security\Authentication\Provider\SamlProvider
        arguments: ["",""]
```
