### ISSUE TITLE
Listener method mismatch when using a UserFactory

### ISSUE THREAD

**Issue by alafon** [hslavich/OneloginSamlBundle#176]
The user factory is by default trying to execute `onSamluserCreated` and `onSamluserModified` which are not available in the default classes `UserCreatedListener` and `UserModifiedListener`

See the error (on 1.6.2 and Sf 3.4):

```
Warning: call_user_func() expects parameter 1 to be a valid callback, class 'Hslavich\OneloginSamlBundle\EventListener\User\UserCreatedListener' does not have a method 'onSamluserCreated'
```

What would you prefer ? Renaming the method or changing the listener definition like this:

```
    hslavich_onelogin_saml.user_created_listener:
        class: Hslavich\OneloginSamlBundle\EventListener\User\UserCreatedListener
        arguments: [""]
        tags:
            - { name: kernel.event_listener, event: saml_user.created, method: onUserCreated }
            - { name: hslavich.saml_user_listener }

    hslavich_onelogin_saml.user_modified_listener:
        class: Hslavich\OneloginSamlBundle\EventListener\User\UserModifiedListener
        arguments: [""]
        tags:
            - { name: kernel.event_listener, event: saml_user.modified, method: onUserModified }
            - { name: hslavich.saml_user_listener }
``` 

Basically, adding the `method` attribute on the listener tags.
