### ISSUE TITLE
You cannot refresh a user from the EntityUserProvider that does not contain an identifier. The user object has to be serialized with its own identifier mapped by Doctrine.

### ISSUE THREAD

**Issue by balazs92117** [hslavich/OneloginSamlBundle#178]
I saw #149 , but the issue still exists (or again). After the recent event based user persistence change (#172 ) the #174 changed the UserCreatedListener's default "needPersist" value to false. This causes the above error. If I change the false to true in Resorces/config/service.php:51 the login works well. So I guess, the system doesn't read the security.firewalls.main.saml.persist_user variable, just uses "false".
It is important this error message appears only at first login, if the user does not yet exists in the DB.
I would create a PR, but I'm not sure how (and where) should I read the config value.

**Comment by a-menshchikov** [comment]
@balazs92117 hi!
Could you show your `security.yaml`, user mapping settings and a stack trace of the above error?

**Comment by balazs92117** [comment]
Thank you for the answer @a-menshchikov! Here are the files:

security.yaml:

```
security:
    providers:
        user_provider:
            # Loads user from user repository
            entity:
                class: App\Entity\User
                property: elteId
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # anonymous: ~
            saml:
                username_attribute: elteid
                # User factory service
                user_factory: my_user_factory
                # Persist new user. Doctrine is required.
                # always_use_default_target_path: true
                persist_user: true
            logout:
                path: /saml/logout
            provider: user_provider
    enable_authenticator_manager: true
```

services.yaml:
```
services:
    my_user_factory:
        class: App\Security\SAMLUserCreator
```

App\Security\SAMLUserCreator:
```<?php

namespace App\Security;

use App\Entity\User;

use Hslavich\OneloginSamlBundle\Security\Authentication\Token\SamlTokenInterface;
use Hslavich\OneloginSamlBundle\Security\User\SamlUserFactoryInterface;
use Symfony\Component\Security\Core\User\UserInterface;

class SAMLUserCreator implements SamlUserFactoryInterface
{
    public function createUser($username, array $attributes = []): UserInterface
    {
		
		if(is_string($username)) {
			$idpAttributes = $attributes;
		} else {
			$idpAttributes = $username->getAttributes();
		}
        $user = new User();
        $user->setRoles(["ROLE_USER"]);
        $user->setElteId($idpAttributes["elteid"][0]);
        $user->setUniqueCode($idpAttributes["urn:oid:1.3.6.1.4.1.11914.0.1.154"][0] == "" ? $idpAttributes["username"][0] : $idpAttributes["urn:oid:1.3.6.1.4.1.11914.0.1.154"][0]);
        return $user;
    }
}
```


App\Entity\User:
```
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

use Hslavich\OneloginSamlBundle\Security\User\SamlUserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements SamlUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $uniqueCode;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="integer")
     */
    private $elteId;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUniqueCode(): ?string
    {
        return $this->uniqueCode;
    }

    public function setUniqueCode(string $uniqueCode): self
    {
        $this->uniqueCode = $uniqueCode;

        return $this;
    }

    public function getUsername(): ?int
    {
        return $this->elteId;
    }
    public function getUserIdentifier(): ?int
    {
        return $this->elteId;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): ?string
    {
        return null;
    }

    public function getSalt(): ?string
    {
        return null;
    }

    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getElteId(): ?int
    {
        return $this->elteId;
    }

	....

	
    /**
     * @return string
     */
    public function serialize()
    {
        return serialize([$this->getId(), $this->getEltesId(), $this->getUniqueCode()]);
    }

    /**
     * @return void
     */
    public function unserialize($serialized)
    {
        list($this->id, $this->elteId, $this->uniqueCode) = unserialize($serialized);
    }
	
	public function setSamlAttributes(array $attributes)
    {
        $this->setRoles(array('ROLE_USER'));
    }



}
```
