### ISSUE TITLE
i can't get the attributes from the Idp 

### ISSUE THREAD

**Issue by TherypromoTrinity** [hslavich/OneloginSamlBundle#193]
hi'
My project is in symfony v5.4
my simpleSAML service provider is in v1.9

When i try to go to the saml_path (here: http://exemple.org/saml/login), i'm redirected to the Identity provider. it send back the saml response with attributes to the service provider but here i have a infinite loop,  i'm redirected auto to http://exemple.org/saml/login

i didn't configure a relaystate...

if i try the connexion from the simpleSAML admin page it's ok, i'm redirected to Idp and i have the saml response with attributes without redirection.

my security.yml
```yml
security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        saml_provider:
            # Basic provider instantiates a user with default roles
            saml:
                user_class: App\Entity\User
                default_roles: ['ROLE_USER']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: saml_provider
            pattern: ^/
            saml:
                username_attribute: uid
                use_attribute_friendly_name: true
                check_path: saml_acs
                login_path: saml_login
            logout:
                path: saml_logout
    access_control:
        - { path: ^/saml/login, roles: PUBLIC_ACCESS }
        - { path: ^/saml/metadata, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
```

i'm loosing my hair..
thanks for help..
Thery
