### ISSUE TITLE
Confused, assertionConsumerService not implemented?

### ISSUE THREAD

**Issue by BillKeenan** [hslavich/OneloginSamlBundle#20]
Hi, 

So your bundle is firing me off to the idp, which works, but then login_check is just hitting assertionConsumerService in SamlController , which is not implemented..

what is supposed to happen here?

**Comment by hslavich** [comment]
The security component would intercept the request to the assertion consumer service and complete the authentication. Are you  experiencing an error?

**Comment by BillKeenan** [comment]
Hey great! your here!

Well it's not being intercepted i guess, 

I'm trying to have the form login as well as saml, here is that section from my security.yml

```
     secured_area:
          pattern: ^/
          form_login:
              failure_handler: loginfailure
              success_handler: loginsuccess
          logout:
                path:   /logout
                target: /
          saml:
              username_attribute: uid
              check_path: /saml/acs
              login_path: /saml/login
              failure_path: /login
              always_use_default_target_path: true

```
