### ISSUE TITLE
signature validation failing

### ISSUE THREAD

**Issue by BillKeenan** [hslavich/OneloginSamlBundle#21]
Hi,

Getting this error

Error: Signature validation failed. SAML Response rejected

I dont see in the config where I'm supposed to set the cert fingerprint of cert. I assume this is why it's failing?

**Comment by BillKeenan** [comment]
nm.

**Comment by hslavich** [comment]
Yep!. In `config.yml`
```
hslavich_onelogin_saml:
    idp:
        ...
        x509cert: '%saml.idp.cert%'
```
