### ISSUE TITLE
Specify SAML users only in dataprovider

### ISSUE THREAD

**Issue by BillKeenan** [hslavich/OneloginSamlBundle#22]
Hi,

How can i provide a different provider for the ACS controller? 

I want to add a 'samluser=true' to the dataprovider class to prevent any trickery, (i have saml and NON saml users).

I tried setting a different provider, but it always seems to just grab the first one listed under providers..

**Comment by hslavich** [comment]
I think you have to tried something like this:

``` yml
providers:
  user_provider1:
    ...
  user_provider2:
    ... 

 firewalls:
   default:
     anonymous: ~
     saml:
       ...
       provider: user_provider1
     form_login:
       ...
       provider: user_provider2
```

More info: http://symfony.com/doc/current/cookbook/security/multiple_user_providers.html

**Comment by BillKeenan** [comment]
I appreciate your response, what seems to be happening, is my form login is using my db provider, but then its calling the saml user provider, as if its chained...


``` 
        default:
          saml:
              username_attribute: email
              check_path: /saml/acs
              login_path: /saml/login
              failure_path: /login
              always_use_default_target_path: true
              provider: saml_provider

          # Traditional login form
          form_login:
              login_path: /login
              check_path: /login_check
              always_use_default_target_path: true
              provider: form_provider

          logout:
                path:   /logout
                target: /

    providers:

        saml_provider:
                id: saml_user_provider
        form_provider:
                id: user_provider

```

So it authenticates, but then the homepage is calling the saml_provider, because it's first i'm sure...

```
 security.INFO: User has been authenticated successfully. {"username":"peter@aic.com"} []

 request.INFO: Matched route "homepage". {"route_parameters":{"_controller":"Authentic\\RegistrarBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"https://bram:9000/app_dev.php/"} []

security.WARNING: Username could not be found in the selected user provider. {"username":null,"provider":"Authentic\\SecurityBundle\\User\\SamlUserProvider"} []
```
