### ISSUE TITLE
SP not working as expected

### ISSUE THREAD

**Issue by sergiovier** [hslavich/OneloginSamlBundle#37]
Hi, I've implemented this bundle in a Symfony 3.2 app. This app doesn't have db nor users, just need to be authenticated throught an IDP.

Now, I can log in at /saml/login successfully, but can't log out. Moreover each request to some resource at this app, it's redirected to IDP, then to ACS endpoint and finally, I get the app resource. 

Do you have some tips? Probably I made some mistakes at setting up my app.

**Comment by hslavich** [comment]
Hi @sergiovier, can you paste security.yml content?
If the app is redirecting on everty request, maybe it is not using session (stateless config)

**Comment by sergiovier** [comment]
Ok, here it is

```
security:
    providers:
        saml_provider:
            saml:
                user_class: SomeBundle\Entity\User
                default_roles: ['ROLE_USER']
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        app:
            pattern:    ^/
            anonymous: ~
            saml:
                username_attribute: uid
                check_path: /saml/acs
                login_path: /saml/login
            logout:
                path: /saml/logout
    access_control:
        - { path: ^/saml/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saml/metadata, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
```

... and thanks for your pattience :smile:
