### ISSUE TITLE
Kef file for cert

### ISSUE THREAD

**Issue by soromamadou** [hslavich/OneloginSamlBundle#44]
Hello, could you please tell me how to configure the key file for x509 certification ?

**Comment by hslavich** [comment]
Hello, you can paste the cert content in the config file, for example:

```
hslavich_onelogin_saml:
    idp:
        ...
        x509cert: "MIICgTCCAeoCCQCbOlrWDdX7FTAN..."
```
