### ISSUE TITLE
Logout broken in Symfony 3.4.10

### ISSUE THREAD

**Issue by nreynis** [hslavich/OneloginSamlBundle#53]
During logout, when the IDP redirect to `/saml/logout` on the SP, an AccessDeniedException is now thrown.
Which result in the user being redirected to the IDP's login page instead of the logout target specified in `security.yml`.

I think (but I'm not totally sure) that this has been introduced by changes made on the default logout_listener in Symfony 3.4.10:
https://symfony.com/blog/symfony-3-4-10-released
https://github.com/symfony/symfony/pull/24805

I have fixed the issue by making `/saml/logout` public:
```yaml
security:
    access_control:
        - { path: ^/saml/(login|logout|metadata), roles: IS_AUTHENTICATED_ANONYMOUSLY }
```

I'm not sure this is the best way to fix it though. I do not have enough knowledge of the inner mechanics of Symfony's SecurityBundle.
