### ISSUE TITLE
Ability to have both logout routes

### ISSUE THREAD

**Issue by umpirsky** [hslavich/OneloginSamlBundle#57]
I want to add:

```yaml
logout:
    path: /saml/logout
```

But have one defined already.

What if one have `logout` defined already?

```yaml
security:
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                check_path: fos_user_security_check
                login_path: /login
            saml:
                # Match SAML attribute 'uid' with username.
                # Uses getNameId() method by default.
                username_attribute: username
                check_path: /saml/acs
                login_path: /saml/login
            logout:
                path: fos_user_security_logout
```

Can it be part of the same firewall?
