### ISSUE TITLE
Routing issue? The response was received at...

### ISSUE THREAD

**Issue by ioulian** [hslavich/OneloginSamlBundle#73]
Hi,

I've just installed this bundle on Symfony 2.7 using dev-master.

I've set all the settings on onelogin and in config.yml but when I navigate to /saml/login it gives me this error:

```
The response was received at http://[LOCAL_DOMAIN]/saml/acs instead of http://[LOCAL_DOMAIN]/saml/login
```

I've did a test with a demo from onelogin and it works (https://developers.onelogin.com/saml/php), but not in the symfony application.

What I'm doing wrong, have anybody encountered the same issue? Can it be that the clean urls are breaking this bundle? (Note that I don't use /app_dev.php/saml/*)

This is my SP settings:

```yaml
sp:
        entityId: 'http://[LOCAL_DOMAIN]/saml/metadata'
        assertionConsumerService:
            url: 'http://[LOCAL_DOMAIN]/saml/acs'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
        singleLogoutService:
            url: 'http://[LOCAL_DOMAIN]/saml/logout'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
```

Thanks

**Comment by hslavich** [comment]
Hi, can you paste your security.yml config?

**Comment by ioulian** [comment]
Hi, thanks for the fast reply!

This is my security.yml:

```yaml
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    [REDACTED]: { password: [REDACTED], roles: 'ROLE_SUPER_ADMIN' }
        fos_userbundle:
            id: fos_user.user_provider.username
        saml_provider:
            # Basic provider instantiates a user with default roles
            saml:
                user_class: '[REDACTED]\[REDACTED]\[REDACTED]Bundle\Entity\User'
                default_roles: ['ROLE_USER']

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: chain_provider
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 7340032
                path:     ~
                domain:   ~
                always_remember_me: false
            saml:
                # Match SAML attribute 'uid' with username.
                # Uses getNameId() method by default.
                username_attribute: uid
                # Use the attribute's friendlyName instead of the name 
                use_attribute_friendly_name: true
                check_path: /saml/acs
                login_path: /saml/login
            logout:
                path: /saml/logout
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saml/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saml/metadata, roles: IS_AUTHENTICATED_ANONYMOUSLY }
```
