### ISSUE TITLE
Redirecting user to original page after auth

### ISSUE THREAD

**Issue by hownowbrowncow** [hslavich/OneloginSamlBundle#79]
Hi,

I'm trying to figure out how i can redirect the user to the page they originally came from instead of the root page. It seems the `relayState` is always set to `/saml/login`. This could be set in the controller while doing `$auth->login($relayStateUrl)` but even if i hard code something in there it's not redirecting me to the correct page. Is this a problem with my config or is it a feature missing from this package? I'm a bit new to symfony and how firewalls work so it's possible i'm overlooking something very simple on my end.

Any help would be appreciated.

```
security:
  providers:
    saml_provider:
      saml:
        user_class: 'App\Security\User'
        default_roles: ['ROLE_USER']

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      pattern: ^/
      saml:
        username_attribute: uid
        check_path: /saml/acs
        login_path: /saml/login
      logout:
        path: /saml/logout

  access_control:
    - { path: ^/saml/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/saml/metadata, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_USER }
```
