### ISSUE TITLE
Question : how i can load roles from database after SAML login to connected User

### ISSUE THREAD

**Issue by MedKhachira** [hslavich/OneloginSamlBundle#91]
Hi every one,
How i can load roles (permissions) from local database after SAML success response using UID ? 

Any help please and thank you.

**Comment by Livda** [comment]
In the method `refreshUser` in your `UserProvider` you should make a call to your database to get the data you want. It could be the roles or more information than just the UID of your connected user

**Comment by marcverney** [comment]
@Livda How should we use our own `UserProvider` ? The documentation only mentions the following configuration (when not using integration with classic login form) :

    providers:
        saml_provider:
            # Basic provider instantiates a user with default roles
            saml:
                user_class: 'AppBundle\Entity\User'
                default_roles: ['ROLE_USER']

If I create a [custom user provider](https://symfony.com/doc/current/security/user_provider.html#creating-a-custom-user-provider), it won't be of the `saml` type, nor will it have the `user_class` and `default_roles` arguments, so I think something will be missing. What is the recommended way to do it ? Could you give a brief example ?

**Comment by Livda** [comment]
@marcverney, I don't know how I've done last year, but I've found an easier way to do this. I've created a `UserFactory` which fill a new user if it's not already created, but I keep the default provider for my User.
Here is my factory:
```php
<?php

namespace App\Security;

use App\Entity\User;
use Hslavich\OneloginSamlBundle\Security\Authentication\Token\SamlTokenInterface;
use Hslavich\OneloginSamlBundle\Security\User\SamlUserFactoryInterface;

class UserFactory implements SamlUserFactoryInterface
{
    private const SAML_PREFIX = 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/';

    public function createUser(SamlTokenInterface $token)
    {
        $attributes = $token->getAttributes();
        $user = new User();
        $user->setRoles(['ROLE_USER']);
        $user->setEmail($attributes[self::SAML_PREFIX . 'emailaddress'][0]);
        $user->setUsername($attributes[self::SAML_PREFIX . 'upn'][0]);
        $user->setFullName($attributes[self::SAML_PREFIX . 'name'][0]);

        return $user;
    }
}
```
And here is the configuration of my `security.yaml`:
```yaml
security:
    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        main:
            pattern: ^/
            anonymous: true
            saml:
                always_use_default_target_path: true
                check_path: /saml/acs
                login_path: /saml/login
                provider: user_provider
                username_attribute: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn
                use_attribute_friendly_name: false
                user_factory: App\Security\UserFactory
                persist_user: true
            logout:
                path: /saml/logout
```
